### ISSUE TITLE
CSS improvements

### ISSUE THREAD

**Issue by imath** [imath/wptribu-theme#5]
Things to add:

```css
/* Titre bandeau */
body.page-about .entry-header .entry-title, 
body.page-template-page-about-hero-landing .entry-header .entry-title {
	font-size: 2.5rem;
	line-height: 3rem;
	margin: auto;
}
/* Picto WP bandeau */
.entry-header .dashicons::before {
	color: white;
	line-height:5rem;
}
/* Paragraphe WP bandeau */
body.page-about .entry-header .entry-description,
body.page-template-page-about-hero-landing .entry-header p.entry-description{
	display:none;
}
p.has-text-align-center.has-medium-font-size{
	hyphens: none;
}
/* Blocs des moments */
body.page-about .entry-content .home-landing .section,
body.page-template-page-about-hero-landing .entry-content .home-landing .section {
	padding: 1rem 0;
}
body.page-about .entry-content .home-landing .section .box,
body.page-template-page-about-hero-landing .entry-content .home-landing .section .box {
	padding: 1rem 1rem 2rem 1rem;
}
/* MOBILE */
@media screen and (max-width:480px) {
	body.page-about .entry-header .entry-title, body.page-template-page-about-hero-landing .entry-header .entry-title {
    		padding: 0;
	}
	.button-group.button-xl .button, .button.button-xl {
		font-weight: 900;
		padding: 0 0.5rem;
		margin: auto;
		margin: -1rem;
	}
}
```
